version: '3'
services:
  backend:
    build:
      context: ./API/Web-API/Web-API/
      dockerfile: Dockerfile
    ports:
      - "7072:80"
    networks:
      - my-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network: